# Generated by Django 3.0.8 on 2020-07-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='회원ID')),
                ('userPW', models.CharField(max_length=20, verbose_name='회원비밀번호')),
                ('nickName', models.CharField(max_length=20, verbose_name='닉네임')),
                ('userEmail', models.EmailField(max_length=200, verbose_name='이메일')),
                ('userAddress', models.CharField(max_length=200, verbose_name='주소')),
                ('userTel', models.CharField(max_length=20, verbose_name='전화번호')),
                ('writerIntro', models.TextField(blank=True, null=True, verbose_name='작가소개')),
                ('userGrade', models.BooleanField(default=False, verbose_name='회원등급')),
                ('userPic', models.ImageField(blank=True, upload_to='userpic/%Y/%m/%d', verbose_name='회원사진')),
            ],
        ),
        migrations.CreateModel(
            name='likebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
