# Generated by Django 3.0.7 on 2020-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likebook',
            name='bookCategoryID',
            field=models.CharField(max_length=20, null=True, verbose_name='관심장르'),
        ),
    ]
