# Generated by Django 3.0.8 on 2020-07-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCategory', models.CharField(choices=[('humanities', '인문'), ('sociology', '사회'), ('poetry', '시집'), ('prose', '산문'), ('essay', '수필'), ('novel', '소설'), ('poem', '시'), ('illustration', '삽화')], max_length=200, verbose_name='카테고리이름')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisherName', models.CharField(max_length=200, verbose_name='출판사이름')),
                ('publisherAddress', models.CharField(max_length=200, verbose_name='출판사주소')),
                ('publisherWeb', models.URLField(verbose_name='출판사홈페이지')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=200, verbose_name='도서제목')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('bookExp', models.TextField(blank=True, null=True, verbose_name='도서설명')),
                ('bookPic', models.ImageField(blank=True, upload_to='books/%Y/%m/%d', verbose_name='도서사진')),
                ('publisherDate', models.DateField(auto_now_add=True, verbose_name='출판일')),
                ('authorID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='저자ID')),
                ('bookCategoryID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.BookCategory', verbose_name='도서카테고리ID')),
                ('publisherID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Publisher', verbose_name='출판사ID')),
            ],
        ),
    ]
