# Generated by Django 3.0.8 on 2020-07-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisherDate',
            field=models.DateField(verbose_name='출판일'),
        ),
    ]
