# Generated by Django 3.0.8 on 2020-07-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writerblogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerblog',
            name='postPic',
            field=models.ImageField(blank=True, null=True, upload_to='writerblogs/postPic', verbose_name='포스트사진'),
        ),
    ]
